// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWy-NLhd3smz9-sIhqHgV2TprJOyvuXno',
    appId: '1:774229332633:web:685154ba4c5d555e311e08',
    messagingSenderId: '774229332633',
    projectId: 'devonly-292406',
    authDomain: 'devonly-292406.firebaseapp.com',
    storageBucket: 'devonly-292406.firebasestorage.app',
    measurementId: 'G-91HXEG1H6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs5OtnT5iumDV7Zw41NzYkvaJhxDoSK7g',
    appId: '1:774229332633:android:523acda02e8f4a31311e08',
    messagingSenderId: '774229332633',
    projectId: 'devonly-292406',
    storageBucket: 'devonly-292406.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAERCa-nG-EqzFSRM98XrOrTdDEZ9tvlLM',
    appId: '1:774229332633:ios:1b2b0c17cd62cb95311e08',
    messagingSenderId: '774229332633',
    projectId: 'devonly-292406',
    storageBucket: 'devonly-292406.firebasestorage.app',
    androidClientId: '774229332633-0pn0k8ao67hfmoqbthm53pibmhd31862.apps.googleusercontent.com',
    iosClientId: '774229332633-dct1i81v9h3ne8tashp4563fg6sdb249.apps.googleusercontent.com',
    iosBundleId: 'com.tegez.exm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAERCa-nG-EqzFSRM98XrOrTdDEZ9tvlLM',
    appId: '1:774229332633:ios:80c1b3f7967bff87311e08',
    messagingSenderId: '774229332633',
    projectId: 'devonly-292406',
    storageBucket: 'devonly-292406.firebasestorage.app',
    androidClientId: '774229332633-0pn0k8ao67hfmoqbthm53pibmhd31862.apps.googleusercontent.com',
    iosClientId: '774229332633-sj84vo63ff0gf53r5cveg6eeaqr6i2c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5GRAQBnzgWZhY8haZ9mODj4iikFBhaTo',
    appId: '1:774229332633:web:c9fe492cc59346fe311e08',
    messagingSenderId: '774229332633',
    projectId: 'devonly-292406',
    authDomain: 'devonly-292406.firebaseapp.com',
    storageBucket: 'devonly-292406.firebasestorage.app',
    measurementId: 'G-4WX1XKNZFH',
  );
}
